/* tslint:disable */
/* eslint-disable */
/**
 * FindMeApi
 * Find Me
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { FindMe } from "../models/index";
import { FindMeFromJSON, FindMeToJSON } from "../models/index";

export interface GetMeByIdRequest {
  meId: number;
}

/**
 * MeApi - interface
 *
 * @export
 * @interface MeApiInterface
 */
export interface MeApiInterface {
  /**
   * Returns a single me
   * @summary Find me by ID
   * @param {number} meId ID of me to return
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof MeApiInterface
   */
  getMeByIdRaw(
    requestParameters: GetMeByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<FindMe>>;

  /**
   * Returns a single me
   * Find me by ID
   */
  getMeById(
    requestParameters: GetMeByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<FindMe>;
}

/**
 *
 */
export class MeApi extends runtime.BaseAPI implements MeApiInterface {
  /**
   * Returns a single me
   * Find me by ID
   */
  async getMeByIdRaw(
    requestParameters: GetMeByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<FindMe>> {
    if (requestParameters["meId"] == null) {
      throw new runtime.RequiredError(
        "meId",
        'Required parameter "meId" was null or undefined when calling getMeById().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/me/{meId}`.replace(
          `{${"meId"}}`,
          encodeURIComponent(String(requestParameters["meId"])),
        ),
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      FindMeFromJSON(jsonValue),
    );
  }

  /**
   * Returns a single me
   * Find me by ID
   */
  async getMeById(
    requestParameters: GetMeByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<FindMe> {
    const response = await this.getMeByIdRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
