/* tslint:disable */
/* eslint-disable */
/**
 * FindMeApi
 * Find Me
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface FindMe
 */
export interface FindMe {
  /**
   *
   * @type {number}
   * @memberof FindMe
   */
  id?: number;
  /**
   *
   * @type {number}
   * @memberof FindMe
   */
  youId?: number;
  /**
   *
   * @type {string}
   * @memberof FindMe
   */
  property?: string;
}

/**
 * Check if a given object implements the FindMe interface.
 */
export function instanceOfFindMe(value: object): value is FindMe {
  return true;
}

export function FindMeFromJSON(json: any): FindMe {
  return FindMeFromJSONTyped(json, false);
}

export function FindMeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): FindMe {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    youId: json["youId"] == null ? undefined : json["youId"],
    property: json["property"] == null ? undefined : json["property"],
  };
}

export function FindMeToJSON(json: any): FindMe {
  return FindMeToJSONTyped(json, false);
}

export function FindMeToJSONTyped(
  value?: FindMe | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    youId: value["youId"],
    property: value["property"],
  };
}
