/* tslint:disable */
/* eslint-disable */
/**
 * FindMeApi
 * Find Me
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface Me
 */
export interface Me {
  /**
   *
   * @type {number}
   * @memberof Me
   */
  youId?: number;
  /**
   *
   * @type {string}
   * @memberof Me
   */
  name?: string;
}

/**
 * Check if a given object implements the Me interface.
 */
export function instanceOfMe(value: object): value is Me {
  return true;
}

export function MeFromJSON(json: any): Me {
  return MeFromJSONTyped(json, false);
}

export function MeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Me {
  if (json == null) {
    return json;
  }
  return {
    youId: json["youId"] == null ? undefined : json["youId"],
    name: json["name"] == null ? undefined : json["name"],
  };
}

export function MeToJSON(json: any): Me {
  return MeToJSONTyped(json, false);
}

export function MeToJSONTyped(
  value?: Me | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    youId: value["youId"],
    name: value["name"],
  };
}
