openapi: 3.1.0
info:
  title: FindYouApi
  description: Find You
  version: 1.0.0
servers:
  - url: "http://localhost:3001/api"
paths:
  /you/{youId}:
    get:
      tags:
        - you
      summary: Find you by ID
      description: Returns a single you
      operationId: getYouById
      parameters:
        - name: youId
          in: path
          description: ID of you to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FindYou"
        "400":
          description: Invalid ID supplied
        "404":
          description: You not found
components:
  schemas:
    FindYou:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        property:
          type: string
          example: relaxed
