openapi: 3.1.0
info:
  title: FindMeApi
  description: Find Me
  version: 1.0.0
servers:
  - url: "http://localhost:3001/api"
paths:
  /me/{meId}:
    get:
      tags:
        - me
      summary: Find me by ID
      description: Returns a single me
      operationId: getMeById
      parameters:
        - name: meId
          in: path
          description: ID of me to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FindMe"
        "400":
          description: Invalid ID supplied
        "404":
          description: Me not found
components:
  schemas:
    FindMe:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        youId:
          type: integer
          format: int64
          example: 123
        property:
          type: string
          example: upset
