/* tslint:disable */
/* eslint-disable */
/**
 * FindYouApi
 * Find You
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { FindYou } from "../models/index";
import { FindYouFromJSON, FindYouToJSON } from "../models/index";

export interface GetYouByIdRequest {
  youId: number;
}

/**
 * YouApi - interface
 *
 * @export
 * @interface YouApiInterface
 */
export interface YouApiInterface {
  /**
   * Returns a single you
   * @summary Find you by ID
   * @param {number} youId ID of you to return
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof YouApiInterface
   */
  getYouByIdRaw(
    requestParameters: GetYouByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<FindYou>>;

  /**
   * Returns a single you
   * Find you by ID
   */
  getYouById(
    requestParameters: GetYouByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<FindYou>;
}

/**
 *
 */
export class YouApi extends runtime.BaseAPI implements YouApiInterface {
  /**
   * Returns a single you
   * Find you by ID
   */
  async getYouByIdRaw(
    requestParameters: GetYouByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<FindYou>> {
    if (requestParameters["youId"] == null) {
      throw new runtime.RequiredError(
        "youId",
        'Required parameter "youId" was null or undefined when calling getYouById().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/you/{youId}`.replace(
          `{${"youId"}}`,
          encodeURIComponent(String(requestParameters["youId"])),
        ),
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      FindYouFromJSON(jsonValue),
    );
  }

  /**
   * Returns a single you
   * Find you by ID
   */
  async getYouById(
    requestParameters: GetYouByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<FindYou> {
    const response = await this.getYouByIdRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
