/* tslint:disable */
/* eslint-disable */
/**
 * FindYouApi
 * Find You
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface You
 */
export interface You {
  /**
   *
   * @type {string}
   * @memberof You
   */
  name?: string;
}

/**
 * Check if a given object implements the You interface.
 */
export function instanceOfYou(value: object): value is You {
  return true;
}

export function YouFromJSON(json: any): You {
  return YouFromJSONTyped(json, false);
}

export function YouFromJSONTyped(json: any, ignoreDiscriminator: boolean): You {
  if (json == null) {
    return json;
  }
  return {
    name: json["name"] == null ? undefined : json["name"],
  };
}

export function YouToJSON(json: any): You {
  return YouToJSONTyped(json, false);
}

export function YouToJSONTyped(
  value?: You | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value["name"],
  };
}
